import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Products from "../components/Products/Products";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Prezko Store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header}>
				<Navbar />
			</header>

			<main className={styles.main}><Products /></main>

			<footer className={styles.footer}>Prezko Store</footer>
		</div>
	);
}
